# Generated by Django 4.2.3 on 2023-07-27 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('interest_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('down_payment', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('loan_term', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('monthly_payment', models.FloatField(blank=True)),
                ('total_loan_amount', models.FloatField(blank=True)),
                ('total_mortgage_amount', models.FloatField(blank=True)),
                ('total_interest_paid', models.FloatField(blank=True)),
            ],
        ),
    ]
